import FooterPage from "./components/footer";
import NaveBarPage from "./components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SUBWAY 써브웨이",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NaveBarPage />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
